title: Farofa - Loja Colaborativa
description: "A Farofa é uma loja colaborativa para artistas independentes. Junte-se a nós!"
baseurl: "" # Deixe em branco se for a raiz do repositório
url: "https://sofaguiar.github.io/lojafarofa.github.io"

theme: minima

# Plugins do Jekyll
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Configurações do GitHub Pages
github:
  is_project_page: true

# Configuração de Navegação
navigation:
  - name: Sobre
    link: "#sobre"
  - name: Como Funciona?
    link: "#funciona"
  - name: Planos
    link: "#planos"
  - name: Como Participar
    link: "#participe"
  - name: Lançamento
    link: "#lancamento"
  - name: Contato
    link: "#contato"

# Excluir arquivos desnecessários do build
exclude:
  - README.md
  - node_modules
  - vendor
